CREATE TABLE NEW_MEDEWERKERS AS SELECT * FROM MEDEWERKERS;

select * from NEW_MEDEWERKERS;

ALTER TABLE NEW_MEDEWERKERS ADD geslacht varchar(3) ADD CONSTRAINT typegeslacht CHECK (geslacht LIKE '[M,V]');

select * from afdelingen;

-- afdelingsnummer genereren
CREATE SEQUENCE test
START WITH 50
INCREMENT BY 10
MAXVALUE 1000
CYCLE;

-- ALTER NUMBER
ALTER TABLE AFDELINGEN MODIFY ANR number(4,0);

-- afdelingen toevoegen
INSERT INTO afdelingen (ANR, NAAM, LOCATIE, HOOFD) VALUES (test.nextval, 'CONTACT', 'HILVERSUM', 7782);
INSERT INTO afdelingen (ANR, NAAM, LOCATIE, HOOFD) VALUES (test.nextval, 'ICT', 'AMSTERDAM', 7782);

CREATE TABLE his_adressentabel(
    POSTCODE varchar(6) NULL,
    HUISNUMMER INT,
    INGANGSDATUM DATE NOT NULL,
    EINDDATUM DATE,
    TELEFOON INT(10) UNIQUE,
    MED_MNR INT NOT NULL,
    FOREIGN KEY (MED_MNR) REFERENCES MEDEWERKERS(mnr),
    CONSTRAINT PK_address PRIMARY KEY (POSTCODE,HUISNUMMER,INGANGSDATUM)
);

ALTER TABLE his_adressentabel ADD CONSTRAINT einddatum CHECK ( EINDDATUM >= INGANGSDATUM ) ADD CONSTRAINT postcodeFormat CHECK (POSTCODE LIKE '[0-9{4},A-Z{2}]');

SELECT * FROM his_adressentabel;

-- H7, 1:
-- CONSTRAINT M_VERK_CHECK CHECK (FUNCTIE = "VERKOPER" AND COMM IS NOT NULL) OR (FUNCTIE != "VERKOPER" AND COMM IS NULL);