-- 1:
--H4, 1:
SELECT CODE, OMSCHRIJVING FROM CURSUSSEN WHERE LENGTE=4;

--H4, 2:
SELECT * FROM MEDEWERKERS ORDER BY FUNCTIE, GBDATUM DESC;

--H4, 3:
SELECT CURSUS FROM UITVOERINGEN WHERE LOCATIE IN ('UTRECHT','MAASTRICHT');

--H4, 5:
SELECT NAAM, VOORL FROM MEDEWERKERS WHERE NOT (NAAM='JANSEN' and VOORL='R');


-- 2:
SELECT (MNR) FROM MEDEWERKERS WHERE NAAM='SMIT'; --7369
insert into UITVOERINGEN (CURSUS, BEGINDATUM, DOCENT, LOCATIE) VALUES ('S02', TO_DATE('2019-03-13', 'yyyy/mm/dd'), 7369, 'LEERDAM');

-- 3:
CREATE SEQUENCE MNR_S
START WITH 8000
INCREMENT BY 1
MAXVALUE 10000
CYCLE;
INSERT INTO MEDEWERKERS (MNR, NAAM, VOORL, FUNCTIE, CHEF, GBDATUM, MAANDSAL, COMM, AFD, GESLACHT) VALUES (MNR_S.nextval, 'ZHOU', 'T', 'STAGAIR', 7902, TO_DATE('1998-01-01', 'yyyy/mm/dd'), 500.00, NULL, 20, NULL);
INSERT INTO MEDEWERKERS (MNR, NAAM, VOORL, FUNCTIE, CHEF, GBDATUM, MAANDSAL, COMM, AFD, GESLACHT) VALUES (MNR_S.nextval, 'DEN HAMER', 'B', 'STAGAIR', 7902, TO_DATE('1998-01-02', 'yyyy/mm/dd'), 450.00, NULL, 20, NULL); 

-- 4:
UPDATE SCHALEN SET SNR= SNR+1 WHERE SNR=5;
INSERT INTO SCHALEN (SNR, ONDERGRENS, BOVENGRENS, TOELAGE) VALUES (5, 3001, 4000, 300);

-- 5:
SELECT * FROM CURSUSSEN;
INSERT INTO CURSUSSEN (CODE, OMSCHRIJVING, TYPE, LENGTE) VALUES ('DP', 'Dataprocessing met Oracle SQL', 'DSG', 8);
INSERT INTO UITVOERINGEN (CURSUS, BEGINDATUM, DOCENT, LOCATIE) VALUES ('DP', TO_DATE('2019-03-14', 'yyyy/mm/dd'), 7566, 'UTRECHT'), ('DP', TO_DATE('2019-03-15', 'yyyy/mm/dd'), 7566, 'UTRECHT'), ('DP', TO_DATE('2019-03-18', 'yyyy/mm/dd'), 7566, 'UTRECHT');
INSERT INTO INSCHRIJVINGEN (CURSIST, CURSUS, BEGINDATUM, EVALUATIE) VALUES (7499, 'DP', TO_DATE('2019-03-14', 'yyyy/mm/dd'), NULL), (7934, 'DP', TO_DATE('2019/03/14', 'yyyy/mm/dd'), NULL), (7788, 'DP', TO_DATE('2019-03-14', 'yyyy/mm/dd'), NULL);

-- 6:
UPDATE MEDEWERKERS SET MAANDSAL=MAANDSAL*1.055 WHERE AFDELINGEN='VERKOOP' AND FUNCTIE!='MANAGER';
UPDATE MEDEWERKERS SET MAANDSAL=MAANDSAL*1.07 WHERE AFDELINGEN='VERKOOP' AND FUNCTIE='MANAGER';

-- 7:
DELETE FROM MEDEWERKERS WHERE NAAM='MARTENS';
DELETE FROM MEDEWERKERS WHERE NAAM='ALDERS';
-- ANTWOORD OP VRAAG "WAAROM LUKT DIT NIET": OMDAT ALDERS BETROKKEN IS IN EEN ANDERE TABEL (INSCHRIJVINGEN)

-- 8:
SELECT * FROM MEDEWERKERS WHERE NAAM='DE KONING'; --7839
INSERT INTO AFDELINGEN (ANR, NAAM, LOCATIE, HOOFD) VALUES (50, 'FINANCIEN', 'LEERDAM', NULL);
INSERT INTO MEDEWERKERS (MNR, NAAM, VOORL, FUNCTIE, CHEF, GBDATUM, MAANDSAL, COMM, AFD, GESLACHT) VALUES (MNR_S.nextval, 'DE KLOET', 'JL', 'MANAGER', 7839, TO_DATE('1999-06-26', 'yyyy/mm/dd'), 4000, NULL, 50, NULL);
SELECT MNR FROM MEDEWERKERS WHERE NAAM='DE KLOET';
UPDATE AFDELINGEN SET HOOFD=8021 WHERE ANR=50;

SELECT * FROM AFDELINGEN;

