-- BOEK OPDRACHTEN:
-- 1a:
SELECT C.CODE, U.BEGINDATUM, C.LENGTE, M.NAAM AS Docent
FROM MEDEWERKERS M, CURSUSSEN C, UITVOERINGEN U
WHERE U.DOCENT = M.MNR AND U.CURSUS = C.CODE;

-- 1b:
SELECT DISTINCT C.CODE, U.BEGINDATUM, C.LENGTE, CASE WHEN U.DOCENT IS NOT NULL THEN M.NAAM ELSE NULL END AS Docent
FROM MEDEWERKERS M, CURSUSSEN C, UITVOERINGEN U WHERE COALESCE(U.DOCENT, -1) IN (M.MNR, -1)
AND U.CURSUS = C.CODE;

-- 2:
SELECT M.NAAM AS Deelnemer, D.NAAM AS Docent
FROM MEDEWERKERS D
    JOIN UITVOERINGEN U ON (U.DOCENT = D.MNR)
    JOIN INSCHRIJVINGEN I USING (CURSUS, BEGINDATUM)
    JOIN MEDEWERKERS M ON (I.CURSIST = M.MNR)
WHERE CURSUS = 'S02';


-- CANVAS OPDRACHTEN:
-- 2:
-- SELECT DISTINCT M1.NAAM
-- FROM MEDEWERKERS M1, MEDEWERKERS M2
-- WHERE M1.MNR = M2.CHEF;
SELECT M.NAAM
FROM AFDELINGEN A, MEDEWERKERS M
WHERE A.HOOFD = M.MNR;


-- 3:
SELECT M.NAAM, A.NAAM AS OPLEIDING, A.LOCATIE
FROM MEDEWERKERS M, AFDELINGEN A
WHERE M.AFD = A.ANR;


-- 4:
SELECT M.NAAM
FROM INSCHRIJVINGEN I, MEDEWERKERS M
WHERE I.CURSUS='S02' AND I.BEGINDATUM LIKE TO_DATE('1999-04-12', 'yyyy-mm-dd') AND I.CURSIST = M.MNR;


-- 5:
SELECT M.NAAM, S.TOELAGE
FROM MEDEWERKERS M, SCHALEN S
WHERE M.MAANDSAL >= S.ONDERGRENS AND M.MAANDSAL < S.BOVENGRENS;