-- 1:
-- H4, 06:
SELECT MNR, FUNCTIE, GBDATUM
FROM MEDEWERKERS
WHERE GBDATUM < TO_DATE('01/JAN/1960', 'DD/MON/YYYY') AND FUNCTIE IN ('TRAINER', 'VERKOPER');
-- H4, 09:
SELECT MNR, NAAM, VOORL FROM MEDEWERKERS WHERE NAAM LIKE '% %';


-- 2:
-- H8, 05:
SELECT CURSUS, BEGINDATUM, COUNT(*)
FROM INSCHRIJVINGEN
WHERE EXTRACT(YEAR FROM BEGINDATUM) = 1999
GROUP BY CURSUS, BEGINDATUM HAVING COUNT(*) >= 3;
-- H8, 07:
SELECT CURSIST, CURSUS FROM INSCHRIJVINGEN GROUP BY CURSIST, CURSUS HAVING COUNT(*) > 1;


-- 3:
SELECT CURSUS, COUNT(*) FROM UITVOERINGEN GROUP BY CURSUS;

-- 4:
SELECT MAX(TO_CHAR(GBDATUM, 'YYYY')) - MIN(TO_CHAR(GBDATUM, 'YYYY')) || ' Jaar vershil' AS VERSCHIL FROM MEDEWERKERS;

SELECT TO_DATE(ROUND(AVG(TO_NUMBER(TO_CHAR(GBDATUM, 'J')))),'J') AS AVERAGE_AGE FROM MEDEWERKERS;

-- 5:
SELECT COUNT(MNR) AS AANTAL_MEDEWERKERS, AVG(NVL(COMM, 0)) AS GEM_ALL, AVG(COMM) AS GEM_VERKOPERS
FROM MEDEWERKERS M;