-- 1:
-- H4, 04:
SELECT CURSIST
FROM INSCHRIJVINGEN
WHERE CURSUS = 'JAV' AND CURSIST IN (
    SELECT CURSIST
    FROM INSCHRIJVINGEN
    WHERE CURSUS = 'XML'
    );


-- H4, 07:
SELECT M.MNR, A.NAAM
FROM MEDEWERKERS M, AFDELINGEN A
WHERE M.AFD = A.ANR AND (A.NAAM != 'OPLEIDINGEN');


-- H4, 08:
SELECT MNR
FROM MEDEWERKERS
WHERE MNR NOT IN (
    SELECT CURSIST
    FROM INSCHRIJVINGEN
    WHERE CURSUS = 'JAV'
    );

-- H4, 10:
SELECT MNR, NAAM, VOORL
FROM MEDEWERKERS
WHERE MNR IN (
    SELECT CHEF
    FROM MEDEWERKERS
    );

-- H4, 11:
SELECT *
FROM UITVOERINGEN U, CURSUSSEN C
WHERE U.CURSUS = C.CODE AND (C.TYPE = 'ALG' AND EXTRACT(YEAR FROM U.BEGINDATUM) = 1999);


-- 2:
-- H8, 04:
SELECT CURSUS, BEGINDATUM, COUNT(I.CURSIST) AS INSCHRIJVINGEN
FROM UITVOERINGEN U
    LEFT OUTER JOIN INSCHRIJVINGEN I USING (CURSUS, BEGINDATUM)
GROUP BY CURSUS, BEGINDATUM
ORDER BY INSCHRIJVINGEN;

-- H8, 09:
SELECT M.VOORL, M.NAAM, COUNT(DISTINCT BEGINDATUM) CURSUSSEN, COUNT(*) CURSISTEN, ROUND(AVG(EVALUATIE), 1) EVALUATIE
FROM MEDEWERKERS M, INSCHRIJVINGEN I
    JOIN UITVOERINGEN U USING (CURSUS, BEGINDATUM)
WHERE M.MNR = U.DOCENT
GROUP BY M.VOORL, M.NAAM;

-- 3:
-- H9, 03:
SELECT M.*
FROM MEDEWERKERS M
WHERE M.MNR NOT IN (
    SELECT U.DOCENT
    FROM UITVOERINGEN U
    WHERE U.DOCENT = M.MNR
    );
