-- 1:
-- H4, 04:
SELECT MNR
FROM MEDEWERKERS M, INSCHRIJVINGEN I
WHERE M.MNR = I.CURSIST AND (I.CURSUS = 'JAV' OR I.CURSUS = 'XML');


-- H4, 07:
SELECT M.MNR, A.NAAM
FROM MEDEWERKERS M, AFDELINGEN A
WHERE M.AFD = A.ANR AND (A.NAAM != 'OPLEIDINGEN');


-- H4, 08:
SELECT M.MNR
FROM MEDEWERKERS M, INSCHRIJVINGEN I
WHERE M.MNR = I.CURSIST AND I.CURSUS != 'JAV';

-- H4, 10:
SELECT M1.NAAM, M1.CHEF, NVL(M1.CHEF, 0)
FROM MEDEWERKERS M1, MEDEWERKERS M2
WHERE M1.MNR = M2.MNR;

-- H4, 11:
SELECT *
FROM UITVOERINGEN U, CURSUSSEN C
WHERE U.CURSUS = C.CODE AND (C.TYPE = 'ALG' AND EXTRACT(YEAR FROM U.BEGINDATUM) = 1999);


-- 2:
-- H8, 04:
SELECT U.CURSUS, U.BEGINDATUM, COUNT(I.CURSUS) AS AANTAL_INSCHRIJVINGEN
FROM UITVOERINGEN U, INSCHRIJVINGEN I
WHERE U.CURSUS = I.CURSUS
GROUP BY U.BEGINDATUM, U.CURSUS;

-- H8, 09:
SELECT DISTINCT M.NAAM, M.VOORL
FROM MEDEWERKERS M, CURSUSSEN C, INSCHRIJVINGEN I
WHERE  M.FUNCTIE = 'TRAINER' AND (I.CURSIST = M.MNR AND C.TYPE = 'ALG');

-- 3:
-- H9, 03:
SELECT M.*
FROM MEDEWERKERS M
WHERE M.MNR NOT IN (SELECT U.DOCENT FROM UITVOERINGEN U);
